### ISSUE TITLE
NullPointerException в Unit тестах

### ISSUE THREAD

**Issue by d3ple** [D3rty/software_engineering_repo#14]
Когда делаю тесты где нужно обращаться к БД, вылетает _"java.lang.NullPointerException"_

- [DbManager.prepareStatement(DbManager.java:61)](https://github.com/D3rty/software_engineering_repo/blob/master/src/main/java/com/d3rty/aaaprotocol/dao/DbManager.java#L61)
- [DbUserSelecting.getUserByLogin(DbUserSelecting.java:22)](https://github.com/D3rty/software_engineering_repo/blob/master/src/main/java/com/d3rty/aaaprotocol/dao/DbUserSelecting.java#L22)
- [CheckingTest.checkLogin(CheckingTest.java:28)](https://github.com/D3rty/software_engineering_repo/blob/master/src/test/java/com/d3rty/aaaprotocol/CheckingTest.java#L28)

```
Running com.d3rty.aaaprotocol.CheckingTest
Tests run: 4, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.15 sec <<< FAILURE!
checkLogin(com.d3rty.aaaprotocol.CheckingTest)  Time elapsed: 1.15 sec  <<< ERROR!
java.lang.NullPointerException
	at com.d3rty.aaaprotocol.dao.DbManager.prepareStatement(DbManager.java:61)
	at com.d3rty.aaaprotocol.dao.DbUserSelecting.getUserByLogin(DbUserSelecting.java:22)
	at com.d3rty.aaaprotocol.CheckingTest.checkLogin(CheckingTest.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
```

**Comment by d3ple** [comment]
Решено: Проблема была в DAO static методах
